import os

IMG_PATH = f".{os.path.sep}resources{os.path.sep}images{os.path.sep}"
FONT_PATH = f".{os.path.sep}resources{os.path.sep}fonts{os.path.sep}"

TILE_WIDTH_ADDITION = 50
TILE_HEIGHT_ADDITION = 0

BETWEEN_TILES_SPACING = 10

BETWEEN_TILE_AND_SCREEN_SPACING = 20

TILE_WIDTH_PERCENTAGE_FROM_SCREEN = 0.18
ARROW_WITH_PERCENTAGE_FROM_SCREEN = 0.05

ASYNC_SLEEP_TIME_ON_EXIT = 0.5

GAME_BASE_COLOR = (127, 169, 6)
