from enum import IntEnum

MISSING_PROPERTY_DEFAULT = -1
NUMBER_CARDS_PER_PLAYER_TWO_OR_THREE_PLAYERS = 5
NUMBER_CARDS_PER_PLAYER_FOUR_PLAYERS = 4
NUMBER_CARDS_COUNT = 20
CARD_INDEX_TO_LETTER_MAP = {0: "a", 1: "b", 2: "c", 3: "d", 4: "e"}
